# 01 Data Cleaning & Preprocessing
This notebook performs data cleaning, missing value handling, datatype conversion, and consistency checks on the pest, weather, and crop yield datasets.

In [3]:
import pandas as pd
import numpy as np
import os

# Load Datasets
pest_weather_df = pd.read_csv('../datasets/pest_weather.csv')
crop_yield_df = pd.read_csv('../datasets/crop_yield.csv')

print('Pest Weather Dataset Shape:', pest_weather_df.shape)
print('Crop Yield Dataset Shape:', crop_yield_df.shape)

Pest Weather Dataset Shape: (249700, 11)
Crop Yield Dataset Shape: (195, 8)

In [4]:
# Check missing values
print('--- Pest Weather Missing Values ---')
print(pest_weather_df.isnull().sum())

print('\n--- Crop Yield Missing Values ---')
print(crop_yield_df.isnull().sum())

--- Pest Weather Missing Values ---
State            0
District         0
Crop             0
Crop_Category    0
Sowing_Season    0
Season           0
Rainfall_mm      0
Temperature      0
Humidity         0
Pest_Name        0
Outbreak         0
dtype: int64

--- Crop Yield Missing Values ---
State              0
District           0
Crop               0
Crop_Category      0
Season             0
Area_Hectares      0
Production_Tons    0
Yield_Kg_Per_Ha    0
dtype: int64

In [5]:
# Data Cleaning and Handling Duplicates
pest_weather_clean = pest_weather_df.drop_duplicates()
crop_yield_clean = crop_yield_df.drop_duplicates()

print('Duplicates removed in pest_weather:', len(pest_weather_df) - len(pest_weather_clean))
print('Duplicates removed in crop_yield:', len(crop_yield_df) - len(crop_yield_clean))

Duplicates removed in pest_weather: 0
Duplicates removed in crop_yield: 0

In [6]:
# Data Type Conversions & Outlier Checks
print(pest_weather_clean.describe())

         Rainfall_mm    Temperature       Humidity
count  249700.000000  249700.000000  249700.000000
mean      128.907997      26.762410      63.266138
std       236.254348       3.472114      10.974682
min         0.050000      11.570000      18.150000
25%        23.160000      24.370000      55.870000
50%        52.960000      26.690000      62.990000
75%       137.710000      29.080000      70.280000
max      7468.320000      41.400000     100.000000

In [7]:
import sys
print(sys.executable)

c:\Users\admin\AppData\Local\Programs\Python\Python312\python.exe

In [8]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

3.0.5
2.5.2

In [9]:
print("===== Pest Weather Dataset =====")
pest_weather_df.info()

print("\n===== Crop Yield Dataset =====")
crop_yield_df.info()

===== Pest Weather Dataset =====
<class 'pandas.DataFrame'>
RangeIndex: 249700 entries, 0 to 249699
Data columns (total 11 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   State          249700 non-null  str
 1   District       249700 non-null  str
 2   Crop           249700 non-null  str
 3   Crop_Category  249700 non-null  str
 4   Sowing_Season  249700 non-null  str
 5   Season         249700 non-null  str
 6   Rainfall_mm    249700 non-null  float64
 7   Temperature    249700 non-null  float64
 8   Humidity       249700 non-null  float64
 9   Pest_Name      249700 non-null  str
 10  Outbreak       249700 non-null  str
dtypes: float64(3), str(8)
memory usage: 34.4 MB

===== Crop Yield Dataset =====
<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   State            195 non-null    str
 1   District         195 non-null    str
 2   Crop             195 non-null    str
 3   Crop_Category    195 non-null    str
 4   Season           195 non-null    str
 5   Area_Hectares    195 non-null    float64
 6   Production_Tons  195 non-null    float64
 7   Yield_Kg_Per_Ha  195 non-null    float64
dtypes: float64(3), str(5)
memory usage: 19.3 KB

In [10]:
display(pest_weather_df.head())

display(crop_yield_df.head())

,State,District,Crop,Crop_Category,Sowing_Season,Season,Rainfall_mm,Temperature,Humidity,Pest_Name,Outbreak
0,Andhra Pradesh,Guntur,Maize,Cereal,Kharif,Monsoon,599.71,32.44,71.81,Stem Borer,High
1,Andhra Pradesh,Guntur,Maize,Cereal,Kharif,Winter,37.13,23.24,54.74,Fall Armyworm,Medium
2,Andhra Pradesh,Guntur,Maize,Cereal,Kharif,Monsoon,14.75,28.01,57.19,Shoot Fly,High
3,Andhra Pradesh,Guntur,Maize,Cereal,Kharif,Winter,9.80,28.23,62.01,Stem Borer,High
4,Andhra Pradesh,Guntur,Maize,Cereal,Kharif,Winter,3.86,20.74,65.62,Fall Armyworm,Low

,State,District,Crop,Crop_Category,Season,Area_Hectares,Production_Tons,Yield_Kg_Per_Ha
0,Andhra Pradesh,Guntur,Maize,Cereal,Monsoon,14285.36,52840.12,3698.90
1,Andhra Pradesh,Guntur,Maize,Cereal,Winter,9180.55,41833.84,4556.79
2,Gujarat,Ahmedabad,Wheat,Cereal,Summer,2761.92,9061.39,3280.83
3,Maharashtra,Nagpur,Cotton,Fiber,Monsoon,13059.55,5603.07,429.04
4,Maharashtra,Nagpur,Cotton,Fiber,Winter,10767.05,7542.96,700.56

In [11]:
print("Pest Weather Missing Values")
print(pest_weather_df.isnull().sum())

print("\nCrop Yield Missing Values")
print(crop_yield_df.isnull().sum())

Pest Weather Missing Values
State            0
District         0
Crop             0
Crop_Category    0
Sowing_Season    0
Season           0
Rainfall_mm      0
Temperature      0
Humidity         0
Pest_Name        0
Outbreak         0
dtype: int64

Crop Yield Missing Values
State              0
District           0
Crop               0
Crop_Category      0
Season             0
Area_Hectares      0
Production_Tons    0
Yield_Kg_Per_Ha    0
dtype: int64

In [12]:
print("Pest Weather Duplicates:", pest_weather_df.duplicated().sum())

print("Crop Yield Duplicates:", crop_yield_df.duplicated().sum())

Pest Weather Duplicates: 0
Crop Yield Duplicates: 0

In [13]:
print(pest_weather_df.dtypes)

print(crop_yield_df.dtypes)

State                str
District             str
Crop                 str
Crop_Category        str
Sowing_Season        str
Season               str
Rainfall_mm      float64
Temperature      float64
Humidity         float64
Pest_Name            str
Outbreak             str
dtype: object
State                  str
District               str
Crop                   str
Crop_Category          str
Season                 str
Area_Hectares      float64
Production_Tons    float64
Yield_Kg_Per_Ha    float64
dtype: object

In [14]:
display(pest_weather_df.describe())

display(crop_yield_df.describe())

         Rainfall_mm    Temperature       Humidity
count  249700.000000  249700.000000  249700.000000
mean      128.907997      26.762410      63.266138
std       236.254348       3.472114      10.974682
min         0.050000      11.570000      18.150000
25%        23.160000      24.370000      55.870000
50%        52.960000      26.690000      62.990000
75%       137.710000      29.080000      70.280000
max      7468.320000      41.400000     100.000000

       Area_Hectares  Production_Tons  Yield_Kg_Per_Ha
count     195.000000       195.000000       195.000000
mean     7542.484513     18075.738667      2405.727487
std      4165.253285     14518.129796      1258.585156
min       633.360000       432.500000       402.530000
25%      3862.150000      6802.055000      1428.380000
50%      7874.280000     14905.810000      2463.050000
75%     10918.600000     25384.695000      3360.130000
max     14855.780000     62787.170000      5135.230000

In [15]:
print("Pest Weather Duplicate Rows :", pest_weather_df.duplicated().sum())
print("Crop Yield Duplicate Rows :", crop_yield_df.duplicated().sum())

Pest Weather Duplicate Rows : 0
Crop Yield Duplicate Rows : 0

In [16]:
print("States :", pest_weather_df["State"].nunique())
print("Districts :", pest_weather_df["District"].nunique())
print("Crops :", pest_weather_df["Crop"].nunique())
print("Pests :", pest_weather_df["Pest_Name"].nunique())
print("Outbreak Classes :", pest_weather_df["Outbreak"].unique())

States : 10
Districts : 30
Crops : 10
Pests : 25
Outbreak Classes : <ArrowStringArray>
['High', 'Medium', 'Low']
Length: 3, dtype: str